apiVersion: v1
entries:
  falco:
  - apiVersion: v2
    appVersion: 0.30.0
    created: "2021-12-28T12:39:57.752209+05:30"
    dependencies:
    - condition: falcosidekick.enabled
      name: falcosidekick
      repository: https://falcosecurity.github.io/charts
      version: 0.3.13
    description: Falco
    digest: e17d3b910aa080b98aee9e59f2202b6892076232e36f05a3df5edfe6782495e9
    home: https://falco.org
    icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/falco/horizontal/color/falco-horizontal-color.svg
    keywords:
    - monitoring
    - security
    - alerting
    - metric
    - troubleshooting
    - run-time
    maintainers:
    - email: cncf-falco-dev@lists.cncf.io
      name: The Falco Authors
    name: falco
    sources:
    - https://github.com/falcosecurity/falco
    urls:
    - charts/falco-1.16.2.tgz
    version: 1.16.2
generated: "2021-12-28T12:39:57.748407+05:30"
